[build]
  command = "pip install -r requirements.txt && gunicorn app:app"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
